name: Build and deploy ASP.Net Core app to Azure Web App - olx-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'olx-api'
  DOTNET_VERSION: '9.x'
  PROJECT_PATH: 'olx_be_api.csproj'
  PUBLISH_DIR: 'publish_output'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet-ef to PATH
        run: |
          $DOTNET_TOOLS_PATH = "$env:USERPROFILE\.dotnet\tools"
          echo "$DOTNET_TOOLS_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Run database migrations
        run: dotnet ef database update --connection "${{ secrets.DB_CONNECTION_STRING_MIGRATION }}" --project "${{ env.PROJECT_PATH }}" --startup-project "${{ env.PROJECT_PATH }}" --verbose
        env:
          DB_CONNECTION_STRING_MIGRATION: ${{ secrets.DB_CONNECTION_STRING_MIGRATION }}

      - name: dotnet publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release -o "${{env.DOTNET_ROOT}}/${{env.PUBLISH_DIR}}"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/${{env.PUBLISH_DIR}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_729459E4852C47F29094B7BE96FBFBC4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E178A8D3DF374AEA89AB47174A0CA4CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A147C672D4545BDA88F5DEE2654A4DD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'olx-api'
          slot-name: 'Production'
          package: .
